version: '3.8'
services:
  web:
    container_name: portfolio
    image: portfolio:local
    build:
      context: .
      dockerfile: compose/dev/Dockerfile
    ports:
      - 8000:80
    volumes:
      - /node_modules:/app/node_modules